src/comps/context/ThemeProvider.tsx
Revised color scheme(s) to add tinted colors to background and primary color of ThemeProvider #68
=> Color Scheme Revisions

package-lock.json, package.json, src/App.tsx
Implemented a custom scrollbar to replace the classic scrollbar with an overlay scrollbar that does not affect the position of components on the page. The scrollbar is fully customizable, and has been set to autohide as well as autosize based on the page's content. There is also a listener so that the scrollbar is rerendered upon window resizing to prevent a bug.
Fixes issue #130
=> Custom Scrollbar

src/pages/admin/Rooms.tsx
Changes the useEffect so that it doesn't fetch duplicate data for rooms and allRooms.
=> Fixes #147 - duplicate room reservations data

src/index.tsx, src/pages/Create.tsx
Fixed issue of authenticated user being able to access the chartering page, and added functionality to redirect a logged out user to the landing page if they attempt to access the chartering page while logged out.
=> Unauthenticated user can access chartering page

src/pages/admin/Strikes.tsx
Added a search filter to the strike page that works similar to the catalog page.
=> Fixes #145 - Added search filter for strike page

src/pages/admin/Rooms.tsx, src/pages/admin/SendMessage.tsx
Added search filters to SendMessages and Rooms pages.
=> Fixes #158 - Added search filters to admin pages

CONTRIBUTING.md
To encourage good practices and prevent common pitfalls (leaving indents unformatted, committing erroneous changes), we will publish contributing guidelines.
Before the guidelines are finalized, discussion can occur in this PR thread.
=> RFC: Add contributing guidelines

src/pages/Create.tsx
Fixes #144 - Prevents user from losing progress during club creation, as well as adding a detector for empty or filled fields so that the user is not prompted when they empty the text fields.
=> Forms prevent navaway

src/pages/admin/Rooms.tsx
Fixes #132  - fixed responsive updating issue allowing to edit room data without needing to reload the page. Fixed issue by updating the Rooms component to refresh the list of rooms after a new room is created.
=> Fixed #132 - fixed responsive updating issue 

src/pages/orgs/admin/Meetings.tsx
Fixes #173 - Puts the create meeting button before the meeting lists
=> Fixes #173 - Puts the create meeting button before the meeting lists

src/comps/pages/home/UnauthenticatedLanding.tsx
As requested by David, removed the "View Meetings" button from the Unauthenticated Landing page.
=> Removed "View Meetings" button from Unauth Landing

src/pages/orgs/NotFound.tsx
=> Fix - commas incorrectly used in NotFound.tsx

src/comps/pages/home/UnauthenticatedLanding.tsx, src/comps/ui/LoginButton.tsx, src/comps/ui/LoginGate.tsx, src/pages/AllMeetings.tsx, src/pages/Create.tsx, src/pages/modules/ModuleRouter.tsx, src/pages/modules/attendance/pages/Home.tsx
LoginGate can be used in place of <Box> elements to wrap around pages that require authentication to use. 
Fixes #138.
=> Add LoginGate wrapper component

src/comps/ui/nav/NavBar.tsx
Just did #189 real quick because why not
=> Add archive link

src/App.tsx, src/comps/ui/AlertDisplay.tsx, src/comps/ui/nav/NavBar.tsx
Fetches alerts from alert.stuysu.org, a static fileserver that will serve a JSON with AlertInfo information.
Alerts can be dismissed unless they are of `error` severity, such as a major outage.
Fixes #183.
=> Display alerts on top of screen

src/pages/modules/attendance/pages/MeetingAdminAttendance.tsx
=> Displays user name instead of id for attendance

src/pages/orgs/admin/Members.tsx
=> Add member email display, button to copy

package-lock.json, package.json, tailwind.config.js
npm installed tailwind css and headless ui, and configured tailwind.config.js to include files from public and src
=> Set up Tailwind CSS and Headless UI

src/@types/api.d.ts, src/comps/admin/OrgApproval.tsx, src/comps/admin/OrgEditApproval.tsx, src/comps/context/OrgContext.tsx, src/comps/pages/orgs/admin/OrgEditor.tsx, src/pages/Create.tsx, src/pages/admin/ApprovePending.tsx, src/pages/orgs/admin/Organization.tsx, src/pages/orgs/index.tsx, src/utils/OrgRequirements.ts
=> Add faculty email field

src/comps/pages/catalog/OrgCard.tsx
Please let me know if there are any issues with the formatting changes for the catalog.
=> Reformat organizations in catalog (#253)

.gitignore, src/comps/ui/DisplayLinks.tsx, src/pages/About.tsx, src/pages/Catalog.tsx, src/pages/admin/Announcements.tsx
DisplayLinks has been updated to support newlines and the component has been added to the rendering of announcements. Fixes #233
=> Update DisplayLinks for newlines and About credits

src/comps/ui/AsyncButton.tsx, src/pages/orgs/Overview.tsx
=> Added leave confirmation

src/pages/admin/AddUser.tsx, src/pages/admin/AdminRedirect.tsx, src/pages/admin/Rooms.tsx, src/pages/admin/index.tsx, src/utils/OrgRequirements.ts
Fixes #266 and #231 (same issues)
also fixes #289
=> Admin panel add user

src/comps/pages/orgs/OrgNav.tsx
=> Add attendance button to Admin Tools section of a club page

src/comps/ui/forms/FormDropSelect.tsx, src/comps/ui/forms/FormTextField.tsx, src/pages/Create.tsx
=> Revised required logic for charter forms

src/comps/admin/OrgApproval.tsx, src/comps/admin/OrgEditApproval.tsx, src/comps/pages/catalog/SearchFilter.tsx, src/comps/pages/orgs/OrgInspector.tsx, src/comps/pages/orgs/OrgNav.tsx, src/comps/ui/nav/NavBar.tsx, src/pages/orgs/Overview.tsx, src/pages/orgs/index.tsx
Fix #309
Fix #308
Fix #307
Fix #299
=> Further Mobile UI Fixes

src/config/routes.ts, src/modules/index.tsx
Changed route of Arista landing page so it does not conflict with the club
=> Fix arista linking
